### PR TITLE
fix weird issue with vw units on popUp load

### LINKED ISSUE #238: Menu Display (CSS) is all messed up and I cannot use it.
Menu Display (CSS) is all messed up and I cannot use it. rebooted, cleared cache, removed and re-added extension.
If I INSPECT with DevTools an element in the menu, then it widens up and I can see the menu again.

Windows 10, Chrome Browser.

HubSpotDevMenu_MessedUp

### PR DESCRIPTION
**Pull request by GonzaloTorreras**
Your checklist for this pull request
🚨Please review the guidelines for contributing to this repository.

[?] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Do not pull request to Master please.(when in doubt request Develop branch)
[X] Test to make sure your feature/bugfix doesn't break other features ;)
[X] Write a meaningful description of what your changes are.
[X] Wait patiently and celebrate, you've submitted changes to the extension!

Description
This should fix the width issue with Chrome v91. It closes #238 bug

<3 Thank you!

### CODE REVIEW

**Comment by GonzaloTorreras** [comment]
@TheWebTech If you don't mind checking with me would be happy to discuss pull request workflow and future publishing

**Comment by TheWebTech** [comment]
Hey this is awesome Gonzalo. I was trying a similar fix but wasn't able to get it to work reliably. I'll give your code a test.
Also I'll DM ya on Slack :)

**Review by TheWebTech — APPROVED** [review]
Tested on my end, it appeared to work flawlessly. Way better than the fix I was attempting. I tried something similar to what you did, but it didn't consistently work for some reason. So I was preparing to actually fully gut the transition between the tabs and just literally hide/show the tab contents.

**Comment by TheWebTech** [comment]
Before merging, You need to increase the version number here - it's a requirement of the Chrome web store.

https://github.com/TheWebTech/HubSpot-Developer-Extension/blob/ee942d1eed283e42d7d02a0e6136037cdc7ea918/manifest.json#L4

The important part to Google is just that the version number increases.

In order to make it clear what versions meant I was using [semantic versioning](https://semver.org/).
Basically it just means that the decimals in the number have meaning.
MAJOR.MINOR.PATCH,

MAJOR version when you make changes that are not backwards compatible. (there's no backward versions in chrome so I'd just treat this like if you do a redesign, or a significant batch of updates. For example Google wants Manifest V3 eventually and that'd be worth incrementing this over since a lot of files will be touched.)
MINOR version when you add functionality in a backwards compatible manner. This is basically what you'll do the majority of the time.
PATCH version when you make backwards compatible bug fixes.

No ones going to yell at ya if you don't perfectly follow that. No one really looks at extension versions anyways.

**Pull request merged**
